import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Button, Input, message } from 'antd'
import axios from 'axios'
import { SetStateAction, useState } from 'react'
import Menu from './menu'
import Router from 'next/router';


export default function Login() {
  
  const [id, setId] = useState('');
  const [password, setPassword] = useState('');

  const onChangeId = (e : React.ChangeEvent<HTMLInputElement>) => {
    console.log(e.target.value);
    setId(e.target.value);
  };

  const onChangePassword = (e : React.ChangeEvent<HTMLInputElement>) => {
    console.log(e.target.value);
    setPassword(e.target.value);
  };


  const onGet = () => {
    axios.defaults.baseURL = 'http://localhost:8900';
    axios
      .get(`/auth/get`, {headers: {
        "Content-Type": "application/json",
        Authorization: `${localStorage.getItem('jwt-token')}`
      }})
      .then((response) => {
        if (response.data.Authorization === 'INSIDE API') {
          throw new Error('요청URL이 잘못됐거나 권한이 없음.');
        }
        message.success(response.data.id);
      })
      .catch((e) => {
        console.log(localStorage.getItem('jwt-token'))
        console.log(e);
        
      });
  };

  const login = () => {
    axios.defaults.baseURL = 'http://localhost:8900';
    axios.defaults.withCredentials = true; // withCredentials 전역 설정
    axios.post(`/auth/login`, {
      id: id,
      password: password})
      .then((response) => {
        if (response.data === 'INSIDE API') {
          throw new Error('요청URL이 잘못됐거나 권한이 없음.');
        }
        console.log(response);
        localStorage.setItem('jwt-token', response.data.Authorization);
        message.success(response.data.message);
      })
      .catch((e) => {
        console.log(e);
        console.log(e.response.data);
        message.error(e.response.data.message);
      });
  };

  return (
    <>
      <Head>
        <title>메인</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <Menu />
        <div className={styles.center}>
          <Button onClick={onGet}>토큰확인</Button>
          <hr />
          <Input
            value={id}
            type="text"
            onChange={onChangeId}
            placeholder="id"
          />
          <hr />
          <Input
            value={password}
            type="password"
            onChange={onChangePassword}
            placeholder="password"
          />
          <Button onClick={login}>로그인</Button>
        </div>

      </main>
    </>
  )
}

